In [1]:
import pandas  as pd

In [4]:
data = [["john",23,'Mumbai'],
        ["ALice",28,'Delhi'],
        ["Harry",30,'Chennai'],
        ["Sam",26,'Bhopal']]

df = pd.DataFrame(data , columns=["Name","Age","City"])

df

    Name  Age     City
0   john   23   Mumbai
1  ALice   28    Delhi
2  Harry   30  Chennai
3    Sam   26   Bhopal

In [27]:
data = { 
"Name" : ["John","Alice","Harry","Sam"],
"Age" : [23,28,30,26],
"City" : ["Mumbai","Delhi","Chennai","Bhopal"]
}


df = pd.DataFrame(data)

print(df)

    Name  Age     City
0   John   23   Mumbai
1  Alice   28    Delhi
2  Harry   30  Chennai
3    Sam   26   Bhopal

In [28]:
df.set_index("Name", inplace = True)

df

       Age     City
Name
John    23   Mumbai
Alice   28    Delhi
Harry   30  Chennai
Sam     26   Bhopal

In [31]:
df.reset_index(inplace=True)

In [32]:
df

    Name  Age     City
0   John   23   Mumbai
1  Alice   28    Delhi
2  Harry   30  Chennai
3    Sam   26   Bhopal

In [62]:
df.shape

(4622, 5)

In [106]:
df = pd.read_csv('newdata.csv')

df.index

RangeIndex(start=0, stop=4622, step=1)

In [53]:
df.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='str')

In [54]:
df.values

array([[1, 1, 'Chips and Fresh Tomato Salsa', nan, '$2.39'],
       [1, 1, 'Izze', '[Clementine]', '$3.39'],
       [1, 1, 'Nantucket Nectar', '[Apple]', '$3.39'],
       ...,
       [1834, 1, 'Chicken Salad Bowl',
        '[Fresh Tomato Salsa, [Fajita Vegetables, Pinto Beans, Guacamole, Lettuce]]',
        '$11.25'],
       [1834, 1, 'Chicken Salad Bowl',
        '[Fresh Tomato Salsa, [Fajita Vegetables, Lettuce]]', '$8.75'],
       [1834, 1, 'Chicken Salad Bowl',
        '[Fresh Tomato Salsa, [Fajita Vegetables, Pinto Beans, Lettuce]]',
        '$8.75']], shape=(4622, 5), dtype=object)

In [55]:
df.head(5)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [56]:
df.tail(5)

,order_id,quantity,item_name,choice_description,item_price
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [61]:
df.sample(5)

,order_id,quantity,item_name,choice_description,item_price
1645,665,1,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Red Chi...",$8.49
3744,1497,1,Canned Soft Drink,[Sprite],$1.25
678,280,1,Chips and Guacamole,NaN,$3.99
1569,636,1,Chicken Burrito,"[Tomatillo Green Chili Salsa, [Rice, Pinto Bea...",$8.75
4419,1762,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$9.39

In [65]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

In [66]:
df.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [72]:
df.isnull().sum().sum()

np.int64(1246)

In [74]:
df.duplicated().sum()

np.int64(59)

In [86]:
df.rename( columns = {'order_id' : 'order'})

,order,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [ ]:
df.rename( columns = {'order_id' : 'order'}, inplace = True)

,order,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [ ]:
df.set_index("order_id",inplace= True)

KeyError: "None of ['order_id'] are in the columns"

In [109]:
df

,quantity,item_name,choice_description,item_price
order_id,,,,
1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,Izze,[Clementine],$3.39
1,1,Nantucket Nectar,[Apple],$3.39
1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [130]:
df['item_name'].dtype

df['item_name'].sum()

df['quantity'].max()
df['quantity'].min()
df['quantity'].var()
df['quantity'].std()
df['quantity'].median()


df.sum(numeric_only = True)

df.mean(numeric_only = True)

df.mode()

   quantity     item_name choice_description item_price
0         1  Chicken Bowl        [Diet Coke]      $8.75