In [76]:
import pandas  as pd

In [77]:
data = [["john",23,'Mumbai'],
        ["ALice",28,'Delhi'],
        ["Harry",30,'Chennai'],
        ["Sam",26,'Bhopal']]

df = pd.DataFrame(data , columns=["Name","Age","City"])

df

    Name  Age     City
0   john   23   Mumbai
1  ALice   28    Delhi
2  Harry   30  Chennai
3    Sam   26   Bhopal

In [78]:
data = { 
"Name" : ["John","Alice","Harry","Sam"],
"Age" : [23,28,30,26],
"City" : ["Mumbai","Delhi","Chennai","Bhopal"]
}


df = pd.DataFrame(data)

print(df)

    Name  Age     City
0   John   23   Mumbai
1  Alice   28    Delhi
2  Harry   30  Chennai
3    Sam   26   Bhopal

In [79]:
df.set_index("Name", inplace = True)

df

       Age     City
Name
John    23   Mumbai
Alice   28    Delhi
Harry   30  Chennai
Sam     26   Bhopal

In [80]:
df.reset_index(inplace=True)

In [81]:
df

    Name  Age     City
0   John   23   Mumbai
1  Alice   28    Delhi
2  Harry   30  Chennai
3    Sam   26   Bhopal

In [82]:
df.shape

(4, 3)

In [83]:
df = pd.read_csv('newdata.csv')

df.index

RangeIndex(start=0, stop=4622, step=1)

In [84]:
df.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='str')

In [85]:
df.values

array([[1, 1, 'Chips and Fresh Tomato Salsa', nan, '$2.39'],
       [1, 1, 'Izze', '[Clementine]', '$3.39'],
       [1, 1, 'Nantucket Nectar', '[Apple]', '$3.39'],
       ...,
       [1834, 1, 'Chicken Salad Bowl',
        '[Fresh Tomato Salsa, [Fajita Vegetables, Pinto Beans, Guacamole, Lettuce]]',
        '$11.25'],
       [1834, 1, 'Chicken Salad Bowl',
        '[Fresh Tomato Salsa, [Fajita Vegetables, Lettuce]]', '$8.75'],
       [1834, 1, 'Chicken Salad Bowl',
        '[Fresh Tomato Salsa, [Fajita Vegetables, Pinto Beans, Lettuce]]',
        '$8.75']], shape=(4622, 5), dtype=object)

In [86]:
df.head(5)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [87]:
df.tail(5)

,order_id,quantity,item_name,choice_description,item_price
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [88]:
df.sample(5)

,order_id,quantity,item_name,choice_description,item_price
1504,611,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream...",$8.75
1669,675,1,Barbacoa Soft Tacos,"[Tomatillo Red Chili Salsa, [Rice, Cheese, Sou...",$9.25
3834,1537,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$9.25
1448,588,1,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
2904,1155,1,Canned Soft Drink,[Diet Coke],$1.25

In [89]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

In [90]:
df.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [91]:
df.isnull().sum().sum()

np.int64(1246)

In [92]:
df.duplicated().sum()

np.int64(59)

In [93]:
df.rename( columns = {'order_id' : 'order'})

,order,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [94]:
df.rename( columns = {'order_id' : 'order'}, inplace = True)

In [95]:
# df.set_index("order_id",inplace= True)

In [96]:
df

,order,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [97]:
df['item_name'].dtype

df['item_name'].sum()

df['quantity'].max()
df['quantity'].min()
df['quantity'].var()
df['quantity'].std()
df['quantity'].median()


df.sum(numeric_only = True)

df.mean(numeric_only = True)

df.mode()

   order  quantity     item_name choice_description item_price
0    926         1  Chicken Bowl        [Diet Coke]      $8.75

In [98]:
df

,order,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [99]:
df.rename(columns={ 'order_id': 'id'}, inplace=True)

df

,order,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [100]:
df['item_name']  # for targeting single column 

# df[['id','item_name']] # for targeting multiple columns 

# df[['id','item_name','item_price']]

df[0:4] # targeting rows
df[0:10]

df.iloc[0:4] # targeting rows

,order,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39

In [101]:
df['item_price']

0        $2.39
1        $3.39
2        $3.39
3        $2.39
4       $16.98
         ...
4617    $11.75
4618    $11.75
4619    $11.25
4620     $8.75
4621     $8.75
Name: item_price, Length: 4622, dtype: str

In [102]:


# df['item_price'] = df['item_price'].str.replace('$','',regex=False)

# df.['item_price'].dtype

In [103]:
# df['item_price'].astype(int)

df['item_price'] = df['item_price'].str.replace('$','',regex=False)

df['item_price'].astype('float')

df['item_price'].dtype

In [104]:
# # df['item_price'].isnull().sum()

# df['item_price'] = pd.to_numeric(df['item_price'])

# df['item_price'].between(11,16)

# df[df['item_price'].between(11,16)]


# # df.drop(columns = ['item_price'], inplace=True) 

# df = df.drop (columns= ['item_price'] )

# df['item_price'] = df['item_price'].str.replace('$','',regex=False)

# df['item_price'].unique()

# df['item_price'].dtype.between(11,6)



# m = df['item_price'].between(11,16)

# df[m]

In [105]:
df.duplicated().sum()

np.int64(59)

In [106]:
df.drop_duplicates(inplace=True)

In [107]:
df.duplicated().sum()

np.int64(0)

In [108]:
df.isnull().sum().sum()

np.int64(1228)

In [109]:
# df.dropna(inplace=True)

In [110]:
df.isnull().sum().sum()

np.int64(1228)

In [111]:
# df.fillna(,inplace=True)

In [112]:
# m = df['choice_description'].mode()

In [113]:
# df.fillna(m,inplace=True)

In [114]:
df.head(5)

,order,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [115]:
df

,order,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [116]:
# df['quantity'] = df['quantity'].apply(lambda x:x+1)

In [117]:
df.head(5)

,order,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [142]:
def incre(x):
    if x>10:
        x+=1

    else:
        x+=3

In [143]:
df['quantity'] = df['quantity'].apply(incre)

In [144]:
df

,order,quantity,item_name,choice_description,item_price
0,1,None,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,None,Izze,[Clementine],3.39
2,1,None,Nantucket Nectar,[Apple],3.39
3,1,None,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,None,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,None,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,None,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,None,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,None,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,None,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [120]:
def item_incre(x):
    if x>10:
        x+=1

    else:
        x+=3 
    return x

In [ ]:
# df['new_price'] = df['item_price'].apply(item_incre)

In [122]:
df['item_name'].unique()

<StringArray>
[         'Chips and Fresh Tomato Salsa',
                                  'Izze',
                      'Nantucket Nectar',
 'Chips and Tomatillo-Green Chili Salsa',
                          'Chicken Bowl',
                         'Side of Chips',
                         'Steak Burrito',
                      'Steak Soft Tacos',
                   'Chips and Guacamole',
                  'Chicken Crispy Tacos',
                    'Chicken Soft Tacos',
                       'Chicken Burrito',
                           'Canned Soda',
                      'Barbacoa Burrito',
                      'Carnitas Burrito',
                         'Carnitas Bowl',
                         'Bottled Water',
 'Chips and Tomatillo Green Chili Salsa',
                         'Barbacoa Bowl',
                                 'Chips',
                    'Chicken Salad Bowl',
                            'Steak Bowl',
                   'Barbacoa Soft Tacos',
                        'Veggie Burrito',
                           'Veggie Bowl',
                    'Steak Crispy Tacos',
   'Chips and Tomatillo Red Chili Salsa',
                 'Barbacoa Crispy Tacos',
                     'Veggie Salad Bowl',
    'Chips and Roasted Chili-Corn Salsa',
    'Chips and Roasted Chili Corn Salsa',
                   'Carnitas Soft Tacos',
                         'Chicken Salad',
                     'Canned Soft Drink',
                      'Steak Salad Bowl',
                     '6 Pack Soft Drink',
   'Chips and Tomatillo-Red Chili Salsa',
                                  'Bowl',
                               'Burrito',
                          'Crispy Tacos',
                 'Carnitas Crispy Tacos',
                           'Steak Salad',
     'Chips and Mild Fresh Tomato Salsa',
                     'Veggie Soft Tacos',
                   'Carnitas Salad Bowl',
                   'Barbacoa Salad Bowl',
                                 'Salad',
                   'Veggie Crispy Tacos',
                          'Veggie Salad',
                        'Carnitas Salad']
Length: 50, dtype: str

In [123]:
df['item_name'].nunique()

50

In [127]:
z = df.groupby('item_name')

In [128]:
y = z.get_group('Canned Soda')

In [129]:
y

      order  quantity    item_name choice_description item_price
18        9         2  Canned Soda           [Sprite]       2.18
28       14         1  Canned Soda       [Dr. Pepper]       1.09
51       23         2  Canned Soda     [Mountain Dew]       2.18
53       24         1  Canned Soda           [Sprite]       1.09
107      47         1  Canned Soda       [Dr. Pepper]       1.09
...     ...       ...          ...                ...        ...
3897   1562         1  Canned Soda     [Mountain Dew]       1.09
3926   1575         1  Canned Soda       [Dr. Pepper]       1.09
3936   1578         1  Canned Soda  [Diet Dr. Pepper]       1.09
4008   1604         1  Canned Soda        [Diet Coke]       1.09
4051   1621         1  Canned Soda           [Sprite]       1.09

[102 rows x 5 columns]

In [139]:
df['item_price'].dtype

df['item_price'].astype('float')

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4563, dtype: float64

In [140]:
df['item_price'].dtype