In [4]:
import pandas as pd 
import numpy as np 


print(pd)

<module 'pandas' from 'c:\\Users\\shakti\\Desktop\\Data Science\\Python Libraries\\Pandas\\.venv\\Lib\\site-packages\\pandas\\__init__.py'>

In [ ]:
# 1. Data preprocessing 
#   - handle missing values

# 2. Data Cleaning 
#   -treat null values

# 3. data Transformation 
#   - Sorting , Filtering , modify

# 4. Data Visualization
#   -Plotting

In [17]:
arr = np.arange(1,21)

# print(arr)

# b = pd.Series(arr)



# df = pd.DataFrame(a)


# print(b,type(b))

# print(df,type(df))

# print(pd.DataFrame(a))

a = [arr,arr,arr,arr]

b = pd.DataFrame(arr)


print(arr,a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20]), array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20]), array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20]), array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])]

In [24]:
a = np.arange(1,21)
b = pd.Series(a)



c = pd.DataFrame({'x':a,'y':b,'z':b})

c

     x   y   z
0    1   1   1
1    2   2   2
2    3   3   3
3    4   4   4
4    5   5   5
5    6   6   6
6    7   7   7
7    8   8   8
8    9   9   9
9   10  10  10
10  11  11  11
11  12  12  12
12  13  13  13
13  14  14  14
14  15  15  15
15  16  16  16
16  17  17  17
17  18  18  18
18  19  19  19
19  20  20  20

In [45]:
df = pd.read_csv('data- - data-.csv')

df.head(1)

df.tail(1)

df.info()

df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      5 non-null      str
 1   age       5 non-null      int64
 2   city      5 non-null      str
 3   category  5 non-null      str
 4   sales     5 non-null      int64
 5   a         5 non-null      int64
 6   b         5 non-null      int64
dtypes: int64(4), str(3)
memory usage: 412.0 bytes

             age       sales         a          b
count   5.000000    5.000000  5.000000   5.000000
mean   27.800000  214.000000  3.800000   7.200000
std     4.969909   66.932802  2.387467   2.774887
min    22.000000  120.000000  1.000000   3.000000
25%    25.000000  200.000000  2.000000   6.000000
50%    27.000000  200.000000  4.000000   8.000000
75%    30.000000  250.000000  5.000000   9.000000
max    35.000000  300.000000  7.000000  10.000000

#**Series and attributes**

In [5]:
import pandas as pd

a = [10,20,30,40,50]

dic = {'a':10,'b':20,'c':30,'d':40}

s = pd.Series(dic)

print(s)
print(pd.Series(a))

a    10
b    20
c    30
d    40
dtype: int64
0    10
1    20
2    30
3    40
4    50
dtype: int64

In [15]:
# s.size
# s.dtype
# s.is_unique
# s.index

print(s)
s.head(1)

s.tail(1)

a    10
b    20
c    30
d    40
dtype: int64

d    40
dtype: int64

In [4]:
import numpy as np 

arr = np.arange(100,1000)

s = pd.Series(arr)

s.head(10)

s.tail(10)

NameError: name 'pd' is not defined

Methods

In [24]:
s.sample(5)

301    401
422    522
6      106
18     118
645    745
dtype: int64

In [26]:
s.value_counts()

100    1
663    1
693    1
694    1
695    1
      ..
403    1
404    1
405    1
406    1
999    1
Name: count, Length: 900, dtype: int64

In [28]:
s.sort_values(ascending=False)

899    999
898    998
897    997
896    996
895    995
      ...
4      104
3      103
2      102
1      101
0      100
Length: 900, dtype: int64

In [29]:
s.sort_index()

0      100
1      101
2      102
3      103
4      104
      ...
895    995
896    996
897    997
898    998
899    999
Length: 900, dtype: int64

In [37]:
s.head(100).sample(10).tail(10).sort_values(ascending=False)

92    192
79    179
51    151
49    149
44    144
38    138
33    133
26    126
22    122
5     105
dtype: int64

**Mathematical Functions**

In [ ]:
s.count()  # 900 not null values

np.int64(900)

In [ ]:
arr = np.array([1,7,np.nan,2,4,np.nan,6,np.nan,4,7,2,8,1,1,3,4])

# print(arr)

s = pd.Series(arr)

# print(s)

u = s.size
v = s.count()

# print(u-v)

s.sum()

6.141025641025642

In [61]:
s.product()

np.float64(1806336.0)

In [62]:
s.mean()

np.float64(3.8461538461538463)

In [63]:
s.mode()

0    1.0
1    4.0
dtype: float64

In [66]:
s.var()

6.141025641025642

In [67]:
s.std()

2.4781092875467867

In [68]:
s.max()

8.0

In [69]:
s.min()

1.0

In [71]:
s.describe()

count    13.000000
mean      3.846154
std       2.478109
min       1.000000
25%       2.000000
50%       4.000000
75%       6.000000
max       8.000000
dtype: float64

**Indexing and Slicing**

In [79]:
s.loc[2]

np.float64(nan)

In [80]:
s.iloc[1]

np.float64(7.0)

In [6]:
s = pd.Series([10,20,30,40,50], index=['a','b','c','d','e'])

# print(s)

# s.iloc[-1]

# print(s.iloc[[1,2,3]])

# s.loc[['a','b','c','d','e']]

# s.loc['a']

# print(s.iloc[1:4])

**Editing a Series**

In [29]:
# s[0] = 100

# print(s)

# s.iloc[5]

# s[14] = 25

# s['a':'c'] = [200,300,400]

s['d':'e'] = 25

print(s)

s

a     200
b     300
c     400
d      25
e      25
0     100
14     25
dtype: int64

a     200
b     300
c     400
d      25
e      25
0     100
14     25
dtype: int64

**NULL VALUE HANDLING**

In [ ]:


s.isnull()

a     False
b     False
c     False
d     False
e     False
0     False
14    False
dtype: bool

In [ ]:
arr = np.array([1,7,np.nan,2,4,np.nan,6,np.nan,4,7,2,8,1,1,3,4])

s = pd.Series(arr)

# print(s.isnull().sum)

# s.isnull().sum()
# print(s.notnull())

# print(s.hasnans)

np.int64(3)

**UNIQUE VALUES**

In [ ]:
arr = np.array([1,7,np.nan,2,4,np.nan,6,np.nan,4,7,4,4,2,8,3,1,1,3,4])


s = pd.Series(arr)

s.unique()

s.nunique()

s.is_unique

False