In [4]:
import pandas as pd 
import numpy as np 


print(pd)

<module 'pandas' from 'c:\\Users\\shakti\\Desktop\\Data Science\\Python Libraries\\Pandas\\.venv\\Lib\\site-packages\\pandas\\__init__.py'>

In [ ]:
# 1. Data preprocessing 
#   - handle missing values

# 2. Data Cleaning 
#   -treat null values

# 3. data Transformation 
#   - Sorting , Filtering , modify

# 4. Data Visualization
#   -Plotting

In [17]:
arr = np.arange(1,21)

# print(arr)

# b = pd.Series(arr)



# df = pd.DataFrame(a)


# print(b,type(b))

# print(df,type(df))

# print(pd.DataFrame(a))

a = [arr,arr,arr,arr]

b = pd.DataFrame(arr)


print(arr,a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20]), array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20]), array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20]), array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])]

In [24]:
a = np.arange(1,21)
b = pd.Series(a)



c = pd.DataFrame({'x':a,'y':b,'z':b})

c

     x   y   z
0    1   1   1
1    2   2   2
2    3   3   3
3    4   4   4
4    5   5   5
5    6   6   6
6    7   7   7
7    8   8   8
8    9   9   9
9   10  10  10
10  11  11  11
11  12  12  12
12  13  13  13
13  14  14  14
14  15  15  15
15  16  16  16
16  17  17  17
17  18  18  18
18  19  19  19
19  20  20  20

In [45]:
df = pd.read_csv('data- - data-.csv')

df.head(1)

df.tail(1)

df.info()

df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      5 non-null      str
 1   age       5 non-null      int64
 2   city      5 non-null      str
 3   category  5 non-null      str
 4   sales     5 non-null      int64
 5   a         5 non-null      int64
 6   b         5 non-null      int64
dtypes: int64(4), str(3)
memory usage: 412.0 bytes

             age       sales         a          b
count   5.000000    5.000000  5.000000   5.000000
mean   27.800000  214.000000  3.800000   7.200000
std     4.969909   66.932802  2.387467   2.774887
min    22.000000  120.000000  1.000000   3.000000
25%    25.000000  200.000000  2.000000   6.000000
50%    27.000000  200.000000  4.000000   8.000000
75%    30.000000  250.000000  5.000000   9.000000
max    35.000000  300.000000  7.000000  10.000000